trigger:
- main
- develop
- feature/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'dotnet build $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      displayName: 'dotnet publish $(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'publishedFiles'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - script: echo "Running tests..."

- stage: Deployment
  displayName: 'Deployment Stages'
  jobs:
  - job: DeploymentJob
    displayName: 'Deployment Job'
    steps:
    - script: echo "Deploying application..."

- stage: Approval
  displayName: 'Approval Stage'
  jobs:
  - job: ApprovalJob
    displayName: 'Approval Job'
    steps:
    - script: echo "Waiting for approval..."

- stage: Release
  displayName: 'Release Stage'
  jobs:
  - job: ReleaseJob
    displayName: 'Release Job'
    steps:
    - script: echo "Releasing application..."

