# Starter pipeline
trigger:
- main
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'


variables:
  buildconfiguration: 'Release'


steps:
    
- task: DotNetCoreCLI@2

  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'
   
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration)'
    publishWebProjects: true
  displayName: 'dotnet publish $(buildConfiguration)'


- task: AzureWebApp@1
  inputs:
    azureSubscription: 'testingdot'
    appType: 'webAppLinux'
    appName: 'testing1209'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|6.0'