trigger:
- main
- develop
- feature/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  displayName: 'dotnet publish $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'publishedFiles'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'testingdot'
    appType: 'webAppLinux'
    appName: 'testing1209'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|6.0'
