apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dot-application-hpa
  namespace: dotnetnamespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dot-application
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70


