apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: dotnetnamespace
spec:
  selector:
    app: dotnet-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000